Feature hash map
oleg-olegi/Aston pull request #1
Opened 2024-07-07 19:49 UTC by oleg-olegi

pls check this beautiful code

2024-07-09 07:22 UTC, igorshmidt99 requested changes, later dismissed
Исправить реализацию массива, и связанную логику

2024-07-09 07:22 UTC, igorshmidt99 commented on src/main/java/org/example/HashTable.java
> +        this.table = new LinkedList[size];
Смотри, связанный список образуется, если нода ссылается на следующую ноду
Поэтому стоит сделать массив нод, а не массив линкд листов, которые могут принимать ноды
Когда возникает коллизия, то node.next = newNode

2024-07-09 13:01 UTC, oleg-olegi commented on src/main/java/org/example/HashTable.java
> +        this.table = new LinkedList[size];
полностью переделал. loadFactor  и  саморасширение я не добавлял. только реализация put, get, remove + тесты

2024-07-11 05:10 UTC, oleg-olegi reviewed
ok

2024-07-11 05:11 UTC, merged